## Cluster Template with 40 Clusters {.unnumbered}


### Description

A cluster template created by 'handwriter' with K=40
clusters. This template was created from 100 handwriting samples from the
CSAFE Handwriting Database. This template is suitable for casework.



### Usage

<pre><code class='language-R'>templateK40
</code></pre>


### Format

A list containing the contents of the cluster template.


<dl>
<dt>centers_seed</dt><dd>An integer for the random number generator use to select the
starting cluster centers for the K-Means algorithm.
</dd>
<dt>cluster</dt><dd>A vector of cluster assignments
for each graph used to create the cluster template. The clusters are numbered sequentially 1, 2,...,K.
</dd>
<dt>centers</dt><dd>The final cluster centers produced by the K-Means algorithm.
</dd>
<dt>K</dt><dd>The number of clusters in the template.
</dd>
<dt>n</dt><dd>The number of training graphs to used to create the template.
</dd>
<dt>docnames</dt><dd>A vector that lists the training document from which each graph originated.
</dd>
<dt>writers</dt><dd>A vector that lists the writer of each graph.
</dd>
<dt>iters</dt><dd>The maximum number of iterations for the K-means
algorithm.
</dd>
<dt>changes</dt><dd>A vector of the number of graphs that
changed clusters on each iteration of the K-means algorithm.
</dd>
<dt>outlierCutoff</dt><dd>A vector of the outlier cutoff values calculated on
each iteration of the K-means algorithm.
</dd>
<dt>stop_reason</dt><dd>The reason the
K-means algorithm terminated.
</dd>
<dt>wcd</dt><dd>The within cluster
distances on the final iteration of the K-means algorithm. More specifically,
the distance between each graph and the center of the cluster to which it
was assigned  on each iteration. The output of 'handwriter::make_clustering_template' stores
the within cluster distances on each iteration, but the previous iterations were removed here to reduce the file size.
</dd>
<dt>wcss</dt><dd>A vector of the
within-cluster sum of squares on each iteration of the K-means algorithm.
</dd></dl>



### Details

'handwriter' splits handwriting samples into component shapes
called <em>graphs</em>. The graphs are sorted into 40 clusters with a K-Means
algorithm. See 'handwriter' for more details.



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library(handwriterApp)

# view number of clusters
templateK40$K

# view number of iterations
templateK40$iters

# view cluster centers
templateK40$centers



```
